# Generated by Django 3.2.6 on 2021-09-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    def create_customer(apps, schema_editor):
        # We can't import the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        Customer = apps.get_model("bulk_update", "Customer")
        Customer.objects.update_or_create(
            email="dr@htmx.org", defaults={"name": "Django", "status": True}
        )
        Customer.objects.update_or_create(
            email="brian@htmx.org", defaults={"name": "Brian", "status": True}
        )
        Customer.objects.update_or_create(
            email="celia@htmx.org", defaults={"name": "Celia", "status": True}
        )
        Customer.objects.update_or_create(
            email="emma@htmx.org", defaults={"name": "Emma", "status": True}
        )

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("status", models.BooleanField()),
            ],
        ),
        migrations.RunPython(create_customer),
    ]
