# Generated by Django 3.2.6 on 2021-08-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    def create_contact(apps, schema_editor):
        # We can't import the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        Contact = apps.get_model("click_to_edit", "Contact")
        Contact.objects.create(
            first_name="Django", last_name="Reinhardt", email_address="dr@htmx.org"
        )

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email_address", models.EmailField(max_length=254)),
            ],
        ),
        migrations.RunPython(create_contact),
    ]
